export default {
  SET_BOOKS: 'SET_BOOKS',
  ADD_BOOK: 'ADD_BOOK',
  UPDATE_BOOK: 'UPDATE_BOOK',
  DELETE_BOOK: 'DELETE_BOOK',
  MARK_DONE_BOOK: 'MARK_DONE_BOOK',
  LOAD_USER_DONE: 'LOAD_USER_DONE',
  SET_USER: 'SET_USER'
};
